text_replacement_dict = {
    'abt':'about',
    'alr':'already',
    'altho':'although',
    'amt':'amount',
    'anw':'anyway',
    'appt':'appointment',
    'atm':'at the moment',
    'b':'be',
    'bc':'because',
    'bday':'birthday',
    'brb':'be right back',
    'btw':'by the way',
    'bw':'between',
    'c':'see',
    'cad':'CAD',
    'def':'definitely',
    'dont':'don\'t',
    'dw':'don\'t worry',
    'dwbi':'don\'t worry about it',
    'esp':'especially',
    'fri':'Friday',
    'fs':'for sure',
    'fwd':'forward',
    'gl':'good luck',
    'gn':'good night',
    'goin':'going',
    'hbu':'how about you',
    'idc':'I don\'t care',
    'idk':'I don\'t know',
    'idt':'I don\'t think',
    'idts':'I don\'t think so',
    'ig':'I guess',
    'ik':'I know',
    'incl':'including',
    'ith':'I think',
    'lmk':'let me know',
    'lp':'Little Prince',
    'lyk':'let you know',
    'mon':'Monday',
    'msg':'message',
    'n':'and',
    'nbd':'no big deal',
    'np':'no problem',
    'nth':'nothing',
    'nvm':'nevermind',
    'nw':'no worries',
    'ofc':'of course',
    'omw':'on my way',
    'perf':'perfect',
    'pls':'please',
    'pp':'Petit Prince',
    'ppl':'people',
    'pt':'point',
    'r':'are',
    'rly':'really',
    'rlly':'really',
    'rn':'right now',
    'rnt':'aren\'t',
    'rr':'Red Rising',
    'seriously':'',
    'sry':'sorry',
    'sth':'something',
    'tbf':'to be fair',
    'td':'today',
    'tgt':'together',
    'tgther':'together',
    'tho':'though',
    'thru':'through',
    'thurs':'Thursday',
    'tmrw':'tomorrow',
    'tn':'tonight',
    'tru':'true',
    'tty':'talk to you',
    'ttyl':'talk to you later',
    'tues':'Tuesday',
    'ty':'thank you',
    'u':'you',
    'ur':'you\'re',
    'uv':'you\'ve',
    'w':'with',
    'wdym':'what do you mean',
    'wdyt':'what do you think',
    'whatre':'what\'re',
    'whats':'what\'s',
    'wo':'without',
    'wtv':'whatever',
    'wyd':'what\'re you doing',
    'y':'why',
    'yk':'you know',
    'yw':'you\'re welcome',

    'εγκ':'Ἐγχειρίδιον',
    'επικ':'Ἐπίκτητος',
    'γγ':'γιαγιά',
    'γκπ':'γιαγιά and παππού',
    'πκγ':'παππού and γιαγιά',
    'ππ':'παππού',
    'θκθ':'θείος and θεία',
}